num_trials: 20
train_meta: "~/demo/data/cifar10/train.csv"
eval_meta: "~/demo/data/cifar10/eval.csv"
fixedparams:
  epochs: 200
  piecewise_lr_decay: "1.0,0.1"
  piecewise_boundaries: "100"
hyperparams:
  learning_rate: "0.1,0.05,0.025,0.01,0.005,0.0025"
  optimizer: "momentum,adam,rmsprop"