num_trials: 50
fixedparams:
  epochs: 10
  piecewise_lr_decay: "1.0,0.1"
  piecewise_boundaries: "11"
hyperparams:
  generate:
    learning_rate: "-3.0,-1.0"
  select:
    optimizer: "momentum,adam,rmsprop"