num_trials: 20
train_meta: "~/demo/data/StanfordDogs120/train.csv"
eval_meta: "~/demo/data/StanfordDogs120/eval.csv"
fixedparams:
  epochs: 10
  piecewise_lr_decay: "1.0,0.1"
  piecewise_boundaries: "5"
hyperparams:
  learning_rate: "0.5,0.25,0.1,0.05,0.025,0.01,0.005,0.0025"
  optimizer: "momentum,adam,rmsprop"