num_trials: 20
train_meta: "~/demo/data/cifar10/train.csv"
eval_meta: "~/demo/data/cifar10/eval.csv"
fixedparams:
  epochs: 100
  piecewise_lr_decay: "1.0,0.1"
  piecewise_boundaries: "75"
hyperparams:
  learning_rate: "2.0,1.0,0.5,0.25,0.1"
  optimizer: "momentum"