num_trials: 20
fixedparams:
  epochs: 2
  piecewise_lr_decay: "1.0,0.1"
  piecewise_boundaries: "1"  
hyperparams:
  generate:
    learning_rate: "-5.0,-1.0"
  select:
    optimizer: "momentum,adam,rmsprop"